# Generated by Django 4.2.9 on 2024-02-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0004_remove_appointment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
