# Generated by Django 4.2.4 on 2024-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0008_doctor_details_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_details',
            old_name='approval_status',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
