# Generated by Django 4.2.9 on 2024-01-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0002_appointment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
