# Generated by Django 4.2.9 on 2024-02-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0003_appointment_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_rejected',
        ),
    ]
