# Generated by Django 4.2.4 on 2024-03-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0006_doctor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_details',
            name='specialization',
        ),
    ]
