# Generated by Django 4.2.4 on 2024-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0007_remove_doctor_details_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
