# Generated by Django 4.2.4 on 2024-04-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0009_rename_approval_status_doctor_details_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
