# Generated by Django 4.2.4 on 2024-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0010_appointment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='img',
        ),
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
