# Generated by Django 4.2.4 on 2024-04-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0013_remove_appointment_disease_remove_appointment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skinapp.disease'),
        ),
    ]
