# Generated by Django 4.2.4 on 2024-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0014_appointment_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='disease',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
